name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # checks out the current git commit, so we can use it.
      # read more at https://github.com/orgs/community/discussions/25682
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo "Write your CI workflow here!"
  
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install dependecies
        run: npm install 
      - name: npm test
        run: npm test
<<<<<<< HEAD


=======
>>>>>>> 13eca6158498b0f267dd4ff5bcb4045d07b2278f
      - name: Test the code
        run: echo "Replace this with the test code"
